#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# specs/A11Y.md §C — suite W: colour contrast must not regress.
#
#   bash dev/tests/W/run.sh          (or: npm run test:a11y)
#
# Renders every Storm surface in real chromium against the vault's REAL shipped
# .obsidian/snippets/storm.css, across the whole palette matrix (static dark,
# e-ink light, community dark/light, the shipped default theme file, and five
# palettes generated by the REAL _extract/_buildTheme from synthetic banner
# images), walks every element with text, reads the computed colour and the
# effective background, and fails anything under 4.5:1 (normal text) / 3:1
# (large text and the non-text boundaries that carry meaning).
#
# The engine lives in dev/a11y/ — ONE copy, which this suite drives. It used to
# be duplicated per repo and kept in sync by hand; part 3 below now simply
# checks that no second copy has reappeared.
#
# Asserts against the built vault, so integrate.py is re-run first.
# ═══════════════════════════════════════════════════════════════════════════
set -uo pipefail
cd "$(dirname "$0")/../.."          # → dev/

VAULT=$(node -e 'process.stdout.write(require("./tests/build.js").VAULT())')

OK=0; BAD=0
pass(){ echo "ok  - $1"; OK=$((OK+1)); }
fail(){ echo "FAIL: $1"; BAD=$((BAD+1)); }

echo "== rebuilding the vault from the sources =="
python3 integrate.py --no-install >/dev/null 2>&1 || { echo "FAIL: integrate.py crashed"; exit 1; }
pass "integrate.py rebuilt the vault"

echo
echo "── 1. every stylesheet the audit walks parses ──────────"
for f in "base/.obsidian/snippets/storm.css" "common/storm-additions.css" \
         "$VAULT/.obsidian/snippets/storm.css" \
         "$VAULT/.obsidian/snippets/storm-theme.css"; do
  out=$(npx --no-install csstree-validator "$f" 2>&1)
  rc=$?
  if [ "$rc" -ne 0 ] && printf '%s' "$out" | grep -qi 'could not determine\|not found'; then
    fail "csstree-validator is not installed — run \`npm install\` in dev/ (it is a devDependency)"
  elif [ -z "$out" ]; then pass "csstree-validator clean: ${f#"$VAULT/"}"
  else fail "csstree-validator errors in $f"; echo "$out" | head -10; fi
done

echo
echo "── 2. the fixes are where they belong (cheap guards) ───"
# F2 · the lifted --faint. The old value is 4.34:1 on the worst ground it lands
# on, so it must not come back in any dark palette copy.
if grep -q -- '--faint:#6a7c8c' base/.obsidian/snippets/storm.css common/storm-additions.css; then
  fail "the pre-§C --faint:#6a7c8c is back in a palette block"
else pass "no dark palette declares the pre-§C --faint:#6a7c8c"; fi
# CONTRACT §B moved every palette literal behind `var(--storm-<name>, <literal>)`;
# the literal is unchanged, so the guards below simply look for it in that shape.
n=$(grep -c -- '--faint:var(--storm-faint,#8899a9)' "$VAULT/.obsidian/snippets/storm.css")
[ "$n" = "7" ] && pass "all 7 dark palette copies carry the lifted --faint (as the var() fallback)" \
                || fail "expected 7 copies of --faint:var(--storm-faint,#8899a9) in the shipped sheet, found $n"
# F6 · --btn / --on-accent are declared, so `var(--btn, …)` never falls through
# to a fill that was never contrast-checked.
grep -q -- '--btn:var(--storm-btn,linear-gradient(180deg,#297893,#22718e))' "$VAULT/.obsidian/snippets/storm.css" \
  && pass "the darkened --btn gradient is declared" || fail "--btn is not the §C gradient"
# §B · the generated default snippet must carry the SAME §C values, or a fresh
# vault would ship a theme file that quietly undoes the accessibility pass.
for tok in "faint:#8899a9" "dim:#9db0c1" "text:#e8eff6" "warm:#e0a458" "good:#63d3b0" "accent-deep:#2b8fb5"; do
  grep -q -- "--storm-$tok" "$VAULT/.obsidian/snippets/storm-theme.css" \
    && pass "storm-theme.css default carries --storm-$tok" \
    || fail "storm-theme.css default does not carry --storm-$tok"
done
grep -q 'linear-gradient(180deg,#3aa5c8,#2b8fb5)' "$VAULT/.obsidian/snippets/storm.css" \
  && fail "the pre-§C 2.65:1 button gradient is back" || pass "no rule uses the pre-§C button gradient"
# F3 · state is carried by dashed edges / flat grounds / badges, never by
# `opacity` on a text-bearing container.
if grep -nE '^\s*\.(gc-row|tb-card|nm-row|g-row|g-task|gi-card|hb)[^{]*\{[^}]*opacity:\.' \
     "$VAULT/.obsidian/snippets/storm.css" >/dev/null; then
  fail "a paused/done rule dims a text-bearing element with opacity again:"
  grep -nE '^\s*\.(gc-row|tb-card|nm-row|g-row|g-task|gi-card|hb)[^{]*\{[^}]*opacity:\.' \
     "$VAULT/.obsidian/snippets/storm.css"
else pass "no paused/done rule dims a text-bearing element with opacity"; fi
grep -q 'class="goalsidx dim" style="opacity' common/Goals/*.md \
  && fail "🎯 Goals still sets an inline opacity on the Done group" \
  || pass "🎯 Goals marks the Done group with a class, not an inline opacity"
# F4 · the sub-task checkbox has its own stroke
grep -q '\.tgantt \.tg-box rect{ fill:var(--surface2); stroke:var(--faint)' "$VAULT/.obsidian/snippets/storm.css" \
  && pass "the Timeline sub-task checkbox strokes with --faint" || fail "the checkbox stroke is not --faint"
# F7 · the progress split is a real boundary, not a wash
grep -q '\.gantt \.g-fill{ fill:var(--accent2); opacity:1; stroke:var(--surface)' "$VAULT/.obsidian/snippets/storm.css" \
  && pass "the goal-panel progress split is opaque with a --surface divider" || fail ".g-fill is still a 50% wash"

echo
echo "── 3. the audit engine exists exactly once ─────────────"
# The engine used to be copied into each repo as tests/W/ and kept in sync by
# hand. There is one copy now; a file anywhere else with identical BYTES is that
# mistake coming back (a same-named but different file, like tests/B1/fixtures.js,
# is a different thing and is fine).
DUPES=""
for f in audit.js probe.js palettes.js fixtures.js audit-surfaces.js graphics.js shots.js; do
  [ -f "a11y/$f" ] || { fail "a11y/$f is missing — the audit engine is incomplete"; continue; }
  while IFS= read -r other; do
    [ "$other" = "./a11y/$f" ] && continue
    cmp -s "$other" "a11y/$f" && DUPES="$DUPES ${other#./}"
  done <<EOF
$(find . -name "$f" -not -path "./node_modules/*" -not -path "./build/*")
EOF
done
[ -z "$DUPES" ] && pass "the audit engine exists once, under a11y/ — no byte-identical copies elsewhere" \
                || fail "the audit engine has been duplicated:$DUPES"

echo
echo "── 4. the audit itself ─────────────────────────────────"
LOG=$(mktemp)
node a11y/audit.js >"$LOG" 2>&1; rc=$?
grep -v '^\[page\.error\]' "$LOG" | tail -40
n_ok=$(grep -c '^ok   - ' "$LOG")
n_bad=$(grep -c '^FAIL - ' "$LOG")
OK=$((OK+n_ok)); BAD=$((BAD+n_bad))
if [ "$rc" -ne 0 ] && [ "$n_bad" -eq 0 ]; then fail "a11y/audit.js exited $rc with no FAIL line"; fi
if [ "$rc" -eq 0 ]; then pass "every surface × palette render is at or above threshold"; fi
grep -q '^render problems' "$LOG" && fail "a surface failed to render — the audit measured nothing there"
rm -f "$LOG"

echo
echo "════════════════════════════════════════════════════════"
if [ "$BAD" -eq 0 ]; then
  echo "PASS — $OK assertions, 0 failures (suite W: colour contrast)"
  exit 0
else
  echo "FAIL — $OK passed, $BAD failed (suite W: colour contrast)"
  exit 1
fi
