/* ═══════════════════════════════════════════════════════════════════════════
   dev/paths.js — every path in this repo, resolved from the repo root.

   Nothing under dev/ may hardcode an absolute path: a clone has to work from
   whatever directory it lands in. Node code requires this file (from tests/V
   that is `require("../../paths.js")`) and asks it for a location instead.

   The Python half of the build has the same table in dev/paths.py; the two are
   checked against each other by tests/V/static_checks.py.
   ═══════════════════════════════════════════════════════════════════════════ */
"use strict";
const fs = require("fs");
const path = require("path");

const DEV = __dirname;
const REPO = path.resolve(DEV, "..");

const P = {
  REPO,
  DEV,
  COMMON: path.join(DEV, "common"),
  DASHBOARD: path.join(DEV, "dashboard"),
  BASE: path.join(DEV, "base"),
  BASE_CSS: path.join(DEV, "base/.obsidian/snippets/storm.css"),
  TESTS: path.join(DEV, "tests"),
  A11Y: path.join(DEV, "a11y"),
  TOOLS: path.join(DEV, "tools"),
  SPECS: path.join(DEV, "specs"),
  /* scratch: everything generated by a build that is not the vault itself.
     .gitignored — never commit anything under here. */
  BUILD: path.join(DEV, "build"),
  TERMS: path.join(DEV, "privacy/terms.json"),
  DEFAULT_VARIANT: "template",
};

/* ── variants ───────────────────────────────────────────────────────────────
   A variant is a directory under dev/ holding a variant.json plus the seed
   notes that variant ships. This repo carries exactly one, `template`, which
   builds the vault at the repo root. A private variant is another such
   directory (add it to .gitignore); no variant's data lives in the build code.
   ────────────────────────────────────────────────────────────────────────── */
function variants() {
  return fs.readdirSync(DEV, { withFileTypes: true })
    .filter(e => e.isDirectory() && fs.existsSync(path.join(DEV, e.name, "variant.json")))
    .map(e => e.name)
    .sort();
}

function variant(name) {
  name = name || P.DEFAULT_VARIANT;
  /* A variant is normally a directory name under dev/. A PATH (anything with a
     separator) also works, so a private variant can live outside dev/ and a test
     can build a throwaway one — the build never needs to know the difference. */
  const dir = /[\\/]/.test(name) ? path.resolve(REPO, name) : path.join(DEV, name);
  if (/[\\/]/.test(name)) name = path.basename(dir);
  const cfgPath = path.join(dir, "variant.json");
  if (!fs.existsSync(cfgPath)) {
    throw new Error("no such variant: " + name + " (have: " + variants().join(", ") + ")");
  }
  const cfg = JSON.parse(fs.readFileSync(cfgPath, "utf8"));
  return Object.assign({}, cfg, {
    name,
    seeds: dir,
    /* the assembled Dashboard.md, before integrate.py folds in the shared notes */
    stage: path.join(P.BUILD, name),
    /* the whole vault, freshly built by integrate.py (dev/build/<name>/vault).
       Tests assert against THIS tree: it is what the build produces right now,
       and tests/V proves it is byte-identical to the vault in the repo. */
    built: path.join(P.BUILD, name, "vault"),
    /* where the finished vault lands — repo-relative in variant.json */
    vault: path.resolve(REPO, cfg.vault),
  });
}

/* the vault this repo publishes */
function vault(name) { return variant(name).vault; }

module.exports = Object.assign(P, { variants, variant, vault });
